print("--------------------------Hands on 4------------------------------")
print("--------------Exercise 3-4---------------")
invite = ['Brianna', 'Andrew', 'Stevan']
print()
print(f'{invite[0]}, can you make it to dinner this Saturday?')
print(f'{invite[1]}, can you make it to dinner this Saturday?')
print(f'{invite[2]}, can you make it to dinner this Saturday?')
print()
print("--------------Exercise 3-5---------------")
print()
print(f'{invite[2]}, cannot make it on Saturday.')
invite.pop()
invite.insert(2, 'Jenna')
print(f'{invite[0]}, can you make it to dinner this Saturday?')
print(f'{invite[1]}, can you make it to dinner this Saturday?')
print(f'{invite[2]}, can you make it to dinner this Saturday?')
print()
print("--------------Exercise 3-6---------------")
print()
print('I found a bigger dinner table.')
invite.insert(0, 'Dad')
invite.insert(2, 'Mom')
invite.append('Blake')
print(f'I am inviting {len(invite)} guests to dinner.')
print(f'{invite[0]}, can you make it to dinner this Saturday?')
print(f'{invite[1]}, can you make it to dinner this Saturday?')
print(f'{invite[2]}, can you make it to dinner this Saturday?')
print(f'{invite[3]}, can you make it to dinner this Saturday?')
print(f'{invite[4]}, can you make it to dinner this Saturday?')
print(f'{invite[5]}, can you make it to dinner this Saturday?')
print()
print("--------------Exercise 3-7---------------")
print()
print('The table wont make it in time so I can only invite 2.')
print(f'{invite[0]}, sorry i cant have you over for dinner this Saturday.')
print(f'{invite[1]}, can you make it to dinner this Saturday?')
print(f'{invite[2]}, sorry i cant have you over for dinner this Saturday.')
print(f'{invite[3]}, can you make it to dinner this Saturday?')
print(f'{invite[4]}, sorry i cant have you over for dinner this Saturday.')
print(f'{invite[5]}, sorry i cant have you over for dinner this Saturday.')
invite.pop(5)
invite.pop(4)
invite.pop(2)
invite.pop(0)
print(f'Here is my revised invite list {invite}.')
print()
print("--------------Exercise 3-10---------------")
print()
nintendoConsoles = ['NES', 'SNES', 'N64', 'Game Cube', 'Wii', 'Switch', 'Game Boy','Game Boy Advance', 'Game Boy Advance SP', 'DS', 'DS Lite', '3DS', 'New 3DS']
print(f'Original List: {nintendoConsoles}')
nintendoConsoles.append('2DS')
nintendoConsoles.insert(5, 'Wii U')
nintendoConsoles.insert(7, 'Game Boy Color')
print(f'List after additions: {nintendoConsoles}')
del nintendoConsoles[5]
del nintendoConsoles[11]
print(f'List After deletions: {nintendoConsoles}')
print(f'List with temp sort: {sorted(nintendoConsoles)}')
nintendoConsoles.reverse()
print(f'List sorted in reverse: {nintendoConsoles}')
nintendoConsoles.sort()
print(f'List sorted in alphabetical order: {nintendoConsoles}')
print(f'There are {len(nintendoConsoles)} in the final list.')
print()